### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by ddugovic** [lichess-org/lila-search#134]
I thought this is the module which serves Advanced Search at https://lichess.org/games/search .  Lishogi is considering the same issue as https://github.com/lichess-org/lila/issues/6969 (however I lack a DB seed for Lishogi so I'm trying to address that issue in Lichess first).

Executing `sbt run -v`, I can't get this to resolve:
https://github.com/lichess-org/lila-search/blob/36ff9c970008488aa9eee527211b560f38128ed3/build.sbt#L61

This happens even after I work around other errors (by copying plugin versions from lila and/or lila-fishnet), e.g.:
```
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error]         * org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.2.0, 1.1.1}
[error]             +- org.scala-lang:scala-compiler:2.12.17              (depends on 2.1.0)
[error]             +- com.typesafe.sbt:sbt-native-packager:1.5.2 (scalaVersion=2.12, sbtVersion=1.0) (depends on 1.1.1)
[error]             +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
```

**Comment by ronfromhp** [comment]
> ```
> [error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
> [error]
> [error]         * org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.2.0, 1.1.1}
> [error]             +- org.scala-lang:scala-compiler:2.12.17              (depends on 2.1.0)
> [error]             +- com.typesafe.sbt:sbt-native-packager:1.5.2 (scalaVersion=2.12, sbtVersion=1.0) (depends on 1.1.1)
> [error]             +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
> ```
Did you find any resolution for this? Can you share the solution with me in that case? I'm getting the same errors even after the latest commit

**Comment by ornicar** [comment]
I added a github action to confirm the bug https://github.com/lichess-org/lila-search/actions/runs/3873098249/jobs/6602719923

but for some reason I can't reproduce it locally, it just compiles fine here
